name = "eventsourcing_postgres"
version = "5.1.2"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Postgres event store for the Eventsourcing library"
licences = ["MIT"]
repository = { type = "github", user = "renatillas", repo = "eventsourcing_postgres" }

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.52.0 and < 2.0.0"
eventsourcing = ">= 7.0.0 and < 8.0.0"
pog = ">= 4.1.0 and < 5.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
birdie = ">= 1.2.5 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
taskle = ">= 2.0.0 and < 3.0.0"
asset = ">= 1.2.0 and < 2.0.0"
